uploads = []
outputs = []

[[generated]]
id = "WcEEUR_TAiVJKisajGSnO"
uri = "file://artifacts/envod-kingdom/src/assets/blog-1.png"
type = "image"
title = "container airplane loading"

[[generated]]
id = "x1kCUsDB54dw_sXxHJBpP"
uri = "file://artifacts/envod-kingdom/src/assets/blog-2.png"
type = "image"
title = "logistics truck convoy night"
